### PR TITLE
Changes to nonlinear_poisson_equation examples

### PR DESCRIPTION
**Pull request by kmith**
Set material field interpolation and fixed typos in example. Updated output files to reflect the changes made. Now ex files contain a clean and neat material field.

### CODE REVIEW

**Review by hsorby — COMMENTED** [review]
What tolerance were you expecting for your results?

**Comment by kmith** [comment]
Do you mean the tolerance that needs to be allowed when this example is run on different architecture and under different OSs and the outcome is compared against expected results (e.g. to run ndiff --relative-error etc)?

**Comment by hsorby** [comment]
Yes that is what I mean.  You have presumably run the simulation twice on the same machine and your error is already 1e-10 that seems rather high.

**Comment by kmith** [comment]
I understand now what you are after. Will investigate it and get back to you.

**Comment by kmith** [comment]
This example was tested using the newly setup functional test framework and  passed with a tolerance of 1.0e-14. So, I suggest we set this at 1.0e-12 for the time being. Note that this was tested only on my machine (Ubuntu 16.04  x86_64). Once Jenkins is up and running and if there are issues with regards to tolerances we can revisit it and decide on a sensible tolerance.

**Pull request merged**
